import IISHardware_and_Software_accountingHardwareTypeEController from '../i-i-s-hardware-and-software-accounting-hardware-type-e';

var IISHardware_and_Software_accountingHardwareTypeENewController = IISHardware_and_Software_accountingHardwareTypeEController;
export default IISHardware_and_Software_accountingHardwareTypeENewController;
