//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hardware.
    /// </summary>
    //  *** Start programmer edit section *** (Hardware CustomAttributes)

    //  *** End programmer edit section *** (Hardware CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HardwareE", new string[] {
            "InventoryNumber as \'Inventory number\'",
            "Name as \'Name\'",
            "DateAdded as \'Date added\'",
            "HardwareType as \'Hardware type\'",
            "HardwareType.Name as \'Name\'",
            "Employee as \'Employee\'",
            "Employee.Name as \'Name\'"}, Hidden=new string[] {
            "HardwareType.Name",
            "Employee.Name"})]
    [MasterViewDefineAttribute("HardwareE", "HardwareType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("HardwareE", "Employee", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("HardwareL", new string[] {
            "InventoryNumber as \'Inventory Number\'",
            "Name as \'Name\'",
            "DateAdded as \'Date Added\'",
            "HardwareType.Name as \'Hardware Type\'",
            "Employee.Name as \'Employee\'"})]
    public class Hardware : ICSSoft.STORMNET.DataObject
    {
        
        private string fInventoryNumber;
        
        private string fName;
        
        private System.DateTime fDateAdded;
        
        private IIS.Hardware_and_Software_accounting.HardwareType fHardwareType;
        
        private IIS.Hardware_and_Software_accounting.User fEmployee;
        
        private IIS.Hardware_and_Software_accounting.Workplace fWorkplace;
        
        //  *** Start programmer edit section *** (Hardware CustomMembers)

        //  *** End programmer edit section *** (Hardware CustomMembers)

        
        /// <summary>
        /// InventoryNumber.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.InventoryNumber CustomAttributes)

        //  *** End programmer edit section *** (Hardware.InventoryNumber CustomAttributes)
        [StrLen(255)]
        public virtual string InventoryNumber
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.InventoryNumber Get start)

                //  *** End programmer edit section *** (Hardware.InventoryNumber Get start)
                string result = this.fInventoryNumber;
                //  *** Start programmer edit section *** (Hardware.InventoryNumber Get end)

                //  *** End programmer edit section *** (Hardware.InventoryNumber Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.InventoryNumber Set start)

                //  *** End programmer edit section *** (Hardware.InventoryNumber Set start)
                this.fInventoryNumber = value;
                //  *** Start programmer edit section *** (Hardware.InventoryNumber Set end)

                //  *** End programmer edit section *** (Hardware.InventoryNumber Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.Name CustomAttributes)

        //  *** End programmer edit section *** (Hardware.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.Name Get start)

                //  *** End programmer edit section *** (Hardware.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Hardware.Name Get end)

                //  *** End programmer edit section *** (Hardware.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.Name Set start)

                //  *** End programmer edit section *** (Hardware.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Hardware.Name Set end)

                //  *** End programmer edit section *** (Hardware.Name Set end)
            }
        }
        
        /// <summary>
        /// DateAdded.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.DateAdded CustomAttributes)

        //  *** End programmer edit section *** (Hardware.DateAdded CustomAttributes)
        public virtual System.DateTime DateAdded
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.DateAdded Get start)

                //  *** End programmer edit section *** (Hardware.DateAdded Get start)
                System.DateTime result = this.fDateAdded;
                //  *** Start programmer edit section *** (Hardware.DateAdded Get end)

                //  *** End programmer edit section *** (Hardware.DateAdded Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.DateAdded Set start)

                //  *** End programmer edit section *** (Hardware.DateAdded Set start)
                this.fDateAdded = value;
                //  *** Start programmer edit section *** (Hardware.DateAdded Set end)

                //  *** End programmer edit section *** (Hardware.DateAdded Set end)
            }
        }
        
        /// <summary>
        /// Hardware.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.HardwareType CustomAttributes)

        //  *** End programmer edit section *** (Hardware.HardwareType CustomAttributes)
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.HardwareType HardwareType
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.HardwareType Get start)

                //  *** End programmer edit section *** (Hardware.HardwareType Get start)
                IIS.Hardware_and_Software_accounting.HardwareType result = this.fHardwareType;
                //  *** Start programmer edit section *** (Hardware.HardwareType Get end)

                //  *** End programmer edit section *** (Hardware.HardwareType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.HardwareType Set start)

                //  *** End programmer edit section *** (Hardware.HardwareType Set start)
                this.fHardwareType = value;
                //  *** Start programmer edit section *** (Hardware.HardwareType Set end)

                //  *** End programmer edit section *** (Hardware.HardwareType Set end)
            }
        }
        
        /// <summary>
        /// Hardware.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.Employee CustomAttributes)

        //  *** End programmer edit section *** (Hardware.Employee CustomAttributes)
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.User Employee
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.Employee Get start)

                //  *** End programmer edit section *** (Hardware.Employee Get start)
                IIS.Hardware_and_Software_accounting.User result = this.fEmployee;
                //  *** Start programmer edit section *** (Hardware.Employee Get end)

                //  *** End programmer edit section *** (Hardware.Employee Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.Employee Set start)

                //  *** End programmer edit section *** (Hardware.Employee Set start)
                this.fEmployee = value;
                //  *** Start programmer edit section *** (Hardware.Employee Set end)

                //  *** End programmer edit section *** (Hardware.Employee Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Hardware_and_Software_accounting.Workplace.
        /// </summary>
        //  *** Start programmer edit section *** (Hardware.Workplace CustomAttributes)

        //  *** End programmer edit section *** (Hardware.Workplace CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.Workplace Workplace
        {
            get
            {
                //  *** Start programmer edit section *** (Hardware.Workplace Get start)

                //  *** End programmer edit section *** (Hardware.Workplace Get start)
                IIS.Hardware_and_Software_accounting.Workplace result = this.fWorkplace;
                //  *** Start programmer edit section *** (Hardware.Workplace Get end)

                //  *** End programmer edit section *** (Hardware.Workplace Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Hardware.Workplace Set start)

                //  *** End programmer edit section *** (Hardware.Workplace Set start)
                this.fWorkplace = value;
                //  *** Start programmer edit section *** (Hardware.Workplace Set end)

                //  *** End programmer edit section *** (Hardware.Workplace Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HardwareE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareE", typeof(IIS.Hardware_and_Software_accounting.Hardware));
                }
            }
            
            /// <summary>
            /// "HardwareL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareL", typeof(IIS.Hardware_and_Software_accounting.Hardware));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Hardware.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)
    public class DetailArrayOfHardware : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Hardware_and_Software_accounting.DetailArrayOfHardware members)

        //  *** End programmer edit section *** (IIS.Hardware_and_Software_accounting.DetailArrayOfHardware members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Hardware by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Hardware.
        /// </summary>
        public DetailArrayOfHardware(IIS.Hardware_and_Software_accounting.Workplace fWorkplace) : 
                base(typeof(Hardware), ((ICSSoft.STORMNET.DataObject)(fWorkplace)))
        {
        }
        
        public IIS.Hardware_and_Software_accounting.Hardware this[int index]
        {
            get
            {
                return ((IIS.Hardware_and_Software_accounting.Hardware)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Hardware_and_Software_accounting.Hardware dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
