//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hardware type.
    /// </summary>
    //  *** Start programmer edit section *** (HardwareType CustomAttributes)

    //  *** End programmer edit section *** (HardwareType CustomAttributes)
    [AutoAltered()]
    [Caption("Hardware type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HardwareTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("HardwareTypeL", new string[] {
            "Name as \'Name\'"})]
    public class HardwareType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (HardwareType CustomMembers)

        //  *** End programmer edit section *** (HardwareType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (HardwareType.Name CustomAttributes)

        //  *** End programmer edit section *** (HardwareType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (HardwareType.Name Get start)

                //  *** End programmer edit section *** (HardwareType.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (HardwareType.Name Get end)

                //  *** End programmer edit section *** (HardwareType.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (HardwareType.Name Set start)

                //  *** End programmer edit section *** (HardwareType.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (HardwareType.Name Set end)

                //  *** End programmer edit section *** (HardwareType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HardwareTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareTypeE", typeof(IIS.Hardware_and_Software_accounting.HardwareType));
                }
            }
            
            /// <summary>
            /// "HardwareTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareTypeL", typeof(IIS.Hardware_and_Software_accounting.HardwareType));
                }
            }
        }
    }
}
