//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Software.
    /// </summary>
    //  *** Start programmer edit section *** (Software CustomAttributes)

    //  *** End programmer edit section *** (Software CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SoftwareE", new string[] {
            "Name as \'Name\'",
            "Version as \'Version\'",
            "isFreeware as \'Is freeware\'",
            "Vendor as \'Vendor\'",
            "Vendor.Name as \'Name\'"}, Hidden=new string[] {
            "Vendor.Name"})]
    [MasterViewDefineAttribute("SoftwareE", "Vendor", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Software : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fVersion;
        
        private bool fisFreeware;
        
        private IIS.Hardware_and_Software_accounting.Vendor fVendor;
        
        private IIS.Hardware_and_Software_accounting.Workplace fWorkplace;
        
        //  *** Start programmer edit section *** (Software CustomMembers)

        //  *** End programmer edit section *** (Software CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Software.Name CustomAttributes)

        //  *** End programmer edit section *** (Software.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Software.Name Get start)

                //  *** End programmer edit section *** (Software.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Software.Name Get end)

                //  *** End programmer edit section *** (Software.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Software.Name Set start)

                //  *** End programmer edit section *** (Software.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Software.Name Set end)

                //  *** End programmer edit section *** (Software.Name Set end)
            }
        }
        
        /// <summary>
        /// Version.
        /// </summary>
        //  *** Start programmer edit section *** (Software.Version CustomAttributes)

        //  *** End programmer edit section *** (Software.Version CustomAttributes)
        [StrLen(255)]
        public virtual string Version
        {
            get
            {
                //  *** Start programmer edit section *** (Software.Version Get start)

                //  *** End programmer edit section *** (Software.Version Get start)
                string result = this.fVersion;
                //  *** Start programmer edit section *** (Software.Version Get end)

                //  *** End programmer edit section *** (Software.Version Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Software.Version Set start)

                //  *** End programmer edit section *** (Software.Version Set start)
                this.fVersion = value;
                //  *** Start programmer edit section *** (Software.Version Set end)

                //  *** End programmer edit section *** (Software.Version Set end)
            }
        }
        
        /// <summary>
        /// isFreeware.
        /// </summary>
        //  *** Start programmer edit section *** (Software.isFreeware CustomAttributes)

        //  *** End programmer edit section *** (Software.isFreeware CustomAttributes)
        public virtual bool isFreeware
        {
            get
            {
                //  *** Start programmer edit section *** (Software.isFreeware Get start)

                //  *** End programmer edit section *** (Software.isFreeware Get start)
                bool result = this.fisFreeware;
                //  *** Start programmer edit section *** (Software.isFreeware Get end)

                //  *** End programmer edit section *** (Software.isFreeware Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Software.isFreeware Set start)

                //  *** End programmer edit section *** (Software.isFreeware Set start)
                this.fisFreeware = value;
                //  *** Start programmer edit section *** (Software.isFreeware Set end)

                //  *** End programmer edit section *** (Software.isFreeware Set end)
            }
        }
        
        /// <summary>
        /// Software.
        /// </summary>
        //  *** Start programmer edit section *** (Software.Vendor CustomAttributes)

        //  *** End programmer edit section *** (Software.Vendor CustomAttributes)
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.Vendor Vendor
        {
            get
            {
                //  *** Start programmer edit section *** (Software.Vendor Get start)

                //  *** End programmer edit section *** (Software.Vendor Get start)
                IIS.Hardware_and_Software_accounting.Vendor result = this.fVendor;
                //  *** Start programmer edit section *** (Software.Vendor Get end)

                //  *** End programmer edit section *** (Software.Vendor Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Software.Vendor Set start)

                //  *** End programmer edit section *** (Software.Vendor Set start)
                this.fVendor = value;
                //  *** Start programmer edit section *** (Software.Vendor Set end)

                //  *** End programmer edit section *** (Software.Vendor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Hardware_and_Software_accounting.Workplace.
        /// </summary>
        //  *** Start programmer edit section *** (Software.Workplace CustomAttributes)

        //  *** End programmer edit section *** (Software.Workplace CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.Workplace Workplace
        {
            get
            {
                //  *** Start programmer edit section *** (Software.Workplace Get start)

                //  *** End programmer edit section *** (Software.Workplace Get start)
                IIS.Hardware_and_Software_accounting.Workplace result = this.fWorkplace;
                //  *** Start programmer edit section *** (Software.Workplace Get end)

                //  *** End programmer edit section *** (Software.Workplace Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Software.Workplace Set start)

                //  *** End programmer edit section *** (Software.Workplace Set start)
                this.fWorkplace = value;
                //  *** Start programmer edit section *** (Software.Workplace Set end)

                //  *** End programmer edit section *** (Software.Workplace Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SoftwareE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SoftwareE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SoftwareE", typeof(IIS.Hardware_and_Software_accounting.Software));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Software.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfSoftware CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfSoftware CustomAttributes)
    public class DetailArrayOfSoftware : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware members)

        //  *** End programmer edit section *** (IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Software by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Software.
        /// </summary>
        public DetailArrayOfSoftware(IIS.Hardware_and_Software_accounting.Workplace fWorkplace) : 
                base(typeof(Software), ((ICSSoft.STORMNET.DataObject)(fWorkplace)))
        {
        }
        
        public IIS.Hardware_and_Software_accounting.Software this[int index]
        {
            get
            {
                return ((IIS.Hardware_and_Software_accounting.Software)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Hardware_and_Software_accounting.Software dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
