//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T action.
    /// </summary>
    //  *** Start programmer edit section *** (tAction CustomAttributes)

    //  *** End programmer edit section *** (tAction CustomAttributes)
    public enum tAction
    {
        
        //  *** Start programmer edit section *** (tAction.Install CustomAttributes)

        //  *** End programmer edit section *** (tAction.Install CustomAttributes)
        [Caption("Install")]
        Install,
        
        //  *** Start programmer edit section *** (tAction.Modify CustomAttributes)

        //  *** End programmer edit section *** (tAction.Modify CustomAttributes)
        [Caption("Modify")]
        Modify,
    }
}
