//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T state.
    /// </summary>
    //  *** Start programmer edit section *** (tState CustomAttributes)

    //  *** End programmer edit section *** (tState CustomAttributes)
    public enum tState
    {
        
        //  *** Start programmer edit section *** (tState.Excellent CustomAttributes)

        //  *** End programmer edit section *** (tState.Excellent CustomAttributes)
        [Caption("Excellent")]
        Excellent,
        
        //  *** Start programmer edit section *** (tState.Good CustomAttributes)

        //  *** End programmer edit section *** (tState.Good CustomAttributes)
        [Caption("Good")]
        Good,
        
        //  *** Start programmer edit section *** (tState.Poor CustomAttributes)

        //  *** End programmer edit section *** (tState.Poor CustomAttributes)
        [Caption("Poor")]
        Poor,
    }
}
