//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User.
    /// </summary>
    //  *** Start programmer edit section *** (User CustomAttributes)

    //  *** End programmer edit section *** (User CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("UserE", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "isAdmin as \'Is admin\'"})]
    [View("UserL", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "isAdmin as \'Is admin\'"})]
    public class User : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fSurname;
        
        private bool fisAdmin;
        
        //  *** Start programmer edit section *** (User CustomMembers)

        //  *** End programmer edit section *** (User CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (User.Name CustomAttributes)

        //  *** End programmer edit section *** (User.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (User.Name Get start)

                //  *** End programmer edit section *** (User.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (User.Name Get end)

                //  *** End programmer edit section *** (User.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (User.Name Set start)

                //  *** End programmer edit section *** (User.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (User.Name Set end)

                //  *** End programmer edit section *** (User.Name Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        //  *** Start programmer edit section *** (User.Surname CustomAttributes)

        //  *** End programmer edit section *** (User.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                //  *** Start programmer edit section *** (User.Surname Get start)

                //  *** End programmer edit section *** (User.Surname Get start)
                string result = this.fSurname;
                //  *** Start programmer edit section *** (User.Surname Get end)

                //  *** End programmer edit section *** (User.Surname Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (User.Surname Set start)

                //  *** End programmer edit section *** (User.Surname Set start)
                this.fSurname = value;
                //  *** Start programmer edit section *** (User.Surname Set end)

                //  *** End programmer edit section *** (User.Surname Set end)
            }
        }
        
        /// <summary>
        /// isAdmin.
        /// </summary>
        //  *** Start programmer edit section *** (User.isAdmin CustomAttributes)

        //  *** End programmer edit section *** (User.isAdmin CustomAttributes)
        public virtual bool isAdmin
        {
            get
            {
                //  *** Start programmer edit section *** (User.isAdmin Get start)

                //  *** End programmer edit section *** (User.isAdmin Get start)
                bool result = this.fisAdmin;
                //  *** Start programmer edit section *** (User.isAdmin Get end)

                //  *** End programmer edit section *** (User.isAdmin Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (User.isAdmin Set start)

                //  *** End programmer edit section *** (User.isAdmin Set start)
                this.fisAdmin = value;
                //  *** Start programmer edit section *** (User.isAdmin Set end)

                //  *** End programmer edit section *** (User.isAdmin Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "UserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserE", typeof(IIS.Hardware_and_Software_accounting.User));
                }
            }
            
            /// <summary>
            /// "UserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserL", typeof(IIS.Hardware_and_Software_accounting.User));
                }
            }
        }
    }
}
