//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hardware_and_Software_accounting
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Workplace.
    /// </summary>
    //  *** Start programmer edit section *** (Workplace CustomAttributes)

    //  *** End programmer edit section *** (Workplace CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("WorkplaceE", new string[] {
            "InventoryNumber as \'Inventory number\'",
            "OfficeNumber as \'Office number\'",
            "Place as \'Place\'",
            "Branch as \'Branch\'",
            "Branch.Name as \'Name\'"}, Hidden=new string[] {
            "Branch.Name"})]
    [AssociatedDetailViewAttribute("WorkplaceE", "Software", "SoftwareE", true, "", "Software", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("WorkplaceE", "Hardware", "HardwareE", true, "", "Hardware", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("WorkplaceE", "Branch", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("WorkplaceL", new string[] {
            "InventoryNumber as \'Inventory number\'",
            "OfficeNumber as \'Office number\'",
            "Place as \'Place\'",
            "Branch.Name as \'Name\'"})]
    public class Workplace : ICSSoft.STORMNET.DataObject
    {
        
        private string fInventoryNumber;
        
        private string fOfficeNumber;
        
        private string fPlace;
        
        private IIS.Hardware_and_Software_accounting.BranchOffice fBranch;
        
        private IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware fSoftware;
        
        private IIS.Hardware_and_Software_accounting.DetailArrayOfHardware fHardware;
        
        //  *** Start programmer edit section *** (Workplace CustomMembers)

        //  *** End programmer edit section *** (Workplace CustomMembers)

        
        /// <summary>
        /// InventoryNumber.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.InventoryNumber CustomAttributes)

        //  *** End programmer edit section *** (Workplace.InventoryNumber CustomAttributes)
        [StrLen(255)]
        public virtual string InventoryNumber
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.InventoryNumber Get start)

                //  *** End programmer edit section *** (Workplace.InventoryNumber Get start)
                string result = this.fInventoryNumber;
                //  *** Start programmer edit section *** (Workplace.InventoryNumber Get end)

                //  *** End programmer edit section *** (Workplace.InventoryNumber Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.InventoryNumber Set start)

                //  *** End programmer edit section *** (Workplace.InventoryNumber Set start)
                this.fInventoryNumber = value;
                //  *** Start programmer edit section *** (Workplace.InventoryNumber Set end)

                //  *** End programmer edit section *** (Workplace.InventoryNumber Set end)
            }
        }
        
        /// <summary>
        /// OfficeNumber.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.OfficeNumber CustomAttributes)

        //  *** End programmer edit section *** (Workplace.OfficeNumber CustomAttributes)
        [StrLen(255)]
        public virtual string OfficeNumber
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.OfficeNumber Get start)

                //  *** End programmer edit section *** (Workplace.OfficeNumber Get start)
                string result = this.fOfficeNumber;
                //  *** Start programmer edit section *** (Workplace.OfficeNumber Get end)

                //  *** End programmer edit section *** (Workplace.OfficeNumber Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.OfficeNumber Set start)

                //  *** End programmer edit section *** (Workplace.OfficeNumber Set start)
                this.fOfficeNumber = value;
                //  *** Start programmer edit section *** (Workplace.OfficeNumber Set end)

                //  *** End programmer edit section *** (Workplace.OfficeNumber Set end)
            }
        }
        
        /// <summary>
        /// Place.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.Place CustomAttributes)

        //  *** End programmer edit section *** (Workplace.Place CustomAttributes)
        [StrLen(255)]
        public virtual string Place
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.Place Get start)

                //  *** End programmer edit section *** (Workplace.Place Get start)
                string result = this.fPlace;
                //  *** Start programmer edit section *** (Workplace.Place Get end)

                //  *** End programmer edit section *** (Workplace.Place Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.Place Set start)

                //  *** End programmer edit section *** (Workplace.Place Set start)
                this.fPlace = value;
                //  *** Start programmer edit section *** (Workplace.Place Set end)

                //  *** End programmer edit section *** (Workplace.Place Set end)
            }
        }
        
        /// <summary>
        /// Workplace.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.Branch CustomAttributes)

        //  *** End programmer edit section *** (Workplace.Branch CustomAttributes)
        [NotNull()]
        public virtual IIS.Hardware_and_Software_accounting.BranchOffice Branch
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.Branch Get start)

                //  *** End programmer edit section *** (Workplace.Branch Get start)
                IIS.Hardware_and_Software_accounting.BranchOffice result = this.fBranch;
                //  *** Start programmer edit section *** (Workplace.Branch Get end)

                //  *** End programmer edit section *** (Workplace.Branch Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.Branch Set start)

                //  *** End programmer edit section *** (Workplace.Branch Set start)
                this.fBranch = value;
                //  *** Start programmer edit section *** (Workplace.Branch Set end)

                //  *** End programmer edit section *** (Workplace.Branch Set end)
            }
        }
        
        /// <summary>
        /// Workplace.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.Software CustomAttributes)

        //  *** End programmer edit section *** (Workplace.Software CustomAttributes)
        public virtual IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware Software
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.Software Get start)

                //  *** End programmer edit section *** (Workplace.Software Get start)
                if ((this.fSoftware == null))
                {
                    this.fSoftware = new IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware(this);
                }
                IIS.Hardware_and_Software_accounting.DetailArrayOfSoftware result = this.fSoftware;
                //  *** Start programmer edit section *** (Workplace.Software Get end)

                //  *** End programmer edit section *** (Workplace.Software Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.Software Set start)

                //  *** End programmer edit section *** (Workplace.Software Set start)
                this.fSoftware = value;
                //  *** Start programmer edit section *** (Workplace.Software Set end)

                //  *** End programmer edit section *** (Workplace.Software Set end)
            }
        }
        
        /// <summary>
        /// Workplace.
        /// </summary>
        //  *** Start programmer edit section *** (Workplace.Hardware CustomAttributes)

        //  *** End programmer edit section *** (Workplace.Hardware CustomAttributes)
        public virtual IIS.Hardware_and_Software_accounting.DetailArrayOfHardware Hardware
        {
            get
            {
                //  *** Start programmer edit section *** (Workplace.Hardware Get start)

                //  *** End programmer edit section *** (Workplace.Hardware Get start)
                if ((this.fHardware == null))
                {
                    this.fHardware = new IIS.Hardware_and_Software_accounting.DetailArrayOfHardware(this);
                }
                IIS.Hardware_and_Software_accounting.DetailArrayOfHardware result = this.fHardware;
                //  *** Start programmer edit section *** (Workplace.Hardware Get end)

                //  *** End programmer edit section *** (Workplace.Hardware Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Workplace.Hardware Set start)

                //  *** End programmer edit section *** (Workplace.Hardware Set start)
                this.fHardware = value;
                //  *** Start programmer edit section *** (Workplace.Hardware Set end)

                //  *** End programmer edit section *** (Workplace.Hardware Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "WorkplaceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View WorkplaceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("WorkplaceE", typeof(IIS.Hardware_and_Software_accounting.Workplace));
                }
            }
            
            /// <summary>
            /// "WorkplaceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View WorkplaceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("WorkplaceL", typeof(IIS.Hardware_and_Software_accounting.Workplace));
                }
            }
        }
    }
}
