import IISHardware_and_Software_accountingVendorEController from '../i-i-s-hardware-and-software-accounting-vendor-e';

var IISHardware_and_Software_accountingVendorENewController = IISHardware_and_Software_accountingVendorEController;
export default IISHardware_and_Software_accountingVendorENewController;
